[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Access-Control-Allow-Origin = "*"

[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  [functions.messages]
    runtime = "python3.11"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200